#server:
#    port: 18080
#    address: localhost
#    contextPath: /worktajm-api

spring:
    profiles: cloud
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://us-cdbr-east-05.cleardb.net:3306/ad_59c6bf602049d0e
        databaseName: ad_59c6bf602049d0e
        serverName: us-cdbr-east-05.cleardb.net
        username: be92cd9da4c92e
        password: 030d26b1
        maximumPoolSize: 4

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
