// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.arnellconsulting.tps.webflow;

import com.arnellconsulting.tps.webflow.Registration;
import java.io.Serializable;

privileged aspect Registration_Roo_Serializable {
    
    declare parents: Registration implements Serializable;
    
    private static final long Registration.serialVersionUID = 1L;
    
}
