#Database Configuration
db:
   driver: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/tps?zeroDateTimeBehavior=convertToNull
   username: tps
   password: tps

#Hibernate Configuration
hibernate:
   dialect: org.hibernate.dialect.MySQL5InnoDBDialect
   format_sql: true
   hbm2ddl.auto: validate
   ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
   show_sql: false

server:
   contextPath: /worktajm-api
   port: 8080