// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.arnellconsulting.tps.model;

import com.arnellconsulting.tps.model.Corporate;
import com.arnellconsulting.tps.model.CorporateDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CorporateDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CorporateDataOnDemand: @Component;
    
    private Random CorporateDataOnDemand.rnd = new SecureRandom();
    
    private List<Corporate> CorporateDataOnDemand.data;
    
    public Corporate CorporateDataOnDemand.getNewTransientCorporate(int index) {
        Corporate obj = new Corporate();
        setName(obj, index);
        return obj;
    }
    
    public void CorporateDataOnDemand.setName(Corporate obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Corporate CorporateDataOnDemand.getSpecificCorporate(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Corporate obj = data.get(index);
        Long id = obj.getId();
        return Corporate.findCorporate(id);
    }
    
    public Corporate CorporateDataOnDemand.getRandomCorporate() {
        init();
        Corporate obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Corporate.findCorporate(id);
    }
    
    public boolean CorporateDataOnDemand.modifyCorporate(Corporate obj) {
        return false;
    }
    
    public void CorporateDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Corporate.findCorporateEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Corporate' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Corporate>();
        for (int i = 0; i < 10; i++) {
            Corporate obj = getNewTransientCorporate(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
