// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.arnellconsulting.tps.model;

import com.arnellconsulting.tps.model.Project;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Project_Roo_Configurable {
    
    declare @type: Project: @Configurable;
    
}
