// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.arnellconsulting.tps.webflow;

import com.arnellconsulting.tps.webflow.RegistrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RegistrationTest_Roo_Configurable {
    
    declare @type: RegistrationTest: @Configurable;
    
}
